### ISSUE TITLE
Different Time Zone

### ISSUE THREAD

**Issue by irtec** [ryanbekhen/feserve#11]
![Screen Shot 2023-01-19 at 19 32 24](https://user-images.githubusercontent.com/34168344/213444156-c8c91452-58f2-4109-89e3-84935976f9ab.png)
Om time zone saat starting server berbeda dengan log http, sedangkan kita sudah set time zone-nya di file app.yaml

**Comment by ryanbekhen** [comment]
Terima kasih atas infonya, saya akan memperbaikinya
